name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  
 
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --file Dockerfile -t shimiljas/aks-nodejs-argocd:$GITHUB_REF_NAME-$GITHUB_SHA --load .

      - name: Log in to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username shimiljas --password-stdin
          
      - name: Push Docker image
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker push shimiljas/aks-nodejs-argocd:$GITHUB_REF_NAME-$GITHUB_SHA

      - name: Update manifest file
        run: |
          # Install yq using wget 
          wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq

          # Configure git
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          # Update the container image in the deployment file using yq
          yq e ".spec.template.spec.containers[0].image = \"shimiljas/aks-nodejs-argocd:$GITHUB_REF_NAME-$GITHUB_SHA\"" -i manifests/deployment.yaml
          
          # Add, commit, and push changes
          git add manifests/deployment.yaml
          git commit -m "Update deployment image to $GITHUB_SHA"
          git push origin HEAD:main
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
