name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  
 
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --file Dockerfile -t shimiljas/aks-nodejs-argocd:$GITHUB_REF_NAME-$GITHUB_SHA --load .

      - name: Log in to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username shimiljas --password-stdin
          
      - name: Push Docker image
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker push shimiljas/aks-nodejs-argocd:$GITHUB_REF_NAME-$GITHUB_SHA

      - name: Update manifest file
        run: |    
          # Assuming you have a manifest file named k8s.yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@gmail.com"
          yq eval '.spec.template.spec.containers[0].image = "shimiljas/aks-nodejs-argocd:${{ env.GITHUB_BRANCH }}"' -i manifest/deployment.yml
          
          git add .
          git commit -m "updating newer image"
          git push --set-upstream origin master
